title: JS & TS Playground
description: JavaScript & TypeScript 학습과 실험을 위한 개인 연습 저장소
# GitHub Pages에서 remote_theme 사용
remote_theme: just-the-docs/just-the-docs

# 기본 설정
markdown: kramdown
highlighter: rouge

collections:
  learning:
    output: true

just_the_docs:
  collections:
    learning:
      name: "Learning"        # 사이드바 컬렉션 제목
      nav_fold: true          # 폴더 접기/펼치기
      sort_natural: true
